# GENERATED by scripts/gen-homebrew-formula.mjs from
# packages/cli/binaries/manifest.json. Do not edit by hand — the url, version and
# five SHA-256 values change every release, and a hash somebody retyped is a hash
# nobody can trust.
#
# It fetches the npm platform tarballs, which is where the binaries already
# live — one place, one set of bytes, no GitHub release to create or keep in
# step. Publish this file to the tap repo KodyMike/homebrew-helmwart as
# Formula/helmwart.rb. Users then run:
#   brew tap kodymike/helmwart
#   brew install helmwart
#
# The macOS binaries are signed with a Developer ID and notarised by Apple, so
# Gatekeeper accepts them; `spctl -a -vv` answers "source=Notarized Developer
# ID". They are not stapled, because a bare executable has nowhere to hold a
# ticket — Gatekeeper fetches it from Apple instead. See
# docs/runbooks/signing-macos.md.
class Helmwart < Formula
  desc "Design-time threat modeling for agentic-AI systems, in your CI"
  homepage "https://helmwart.com/cli/"
  version "0.5.4"
  license :cannot_represent # proprietary, free to use — see LICENSE

  on_macos do
    on_arm do
      url "https://registry.npmjs.org/@helmwart/cli-darwin-arm64/-/cli-darwin-arm64-0.5.4.tgz"
      sha256 "136d9ea53cf7daa7c6cf7ffc850de206f77341dd7430d4d601fb0a519883e972"
    end
    on_intel do
      url "https://registry.npmjs.org/@helmwart/cli-darwin-x64/-/cli-darwin-x64-0.5.4.tgz"
      sha256 "a16cd9cf3036f7e1a8f87b8c58033209f8f0345ba3cee4a0d75d396db019842c"
    end
  end

  on_linux do
    on_arm do
      url "https://registry.npmjs.org/@helmwart/cli-linux-arm64/-/cli-linux-arm64-0.5.4.tgz"
      sha256 "80ce2130076bc09ffe7cc6c8b66e1fbebaabdb640754cbb6a6e3914c2df7b222"
    end
    on_intel do
      url "https://registry.npmjs.org/@helmwart/cli-linux-x64/-/cli-linux-x64-0.5.4.tgz"
      sha256 "7d5f23bc82e1606324cc9fb1da77ef28538f7f22973104f6c740d288d58a9c5c"
    end
  end

  # No `depends_on "node"`. The old formula shelled out to node against a
  # readable .mjs bundle; these are self-contained binaries with the runtime
  # compiled in, which is the point of shipping them.

  def install
    # An npm tarball extracts to a single top-level directory that Homebrew
    # strips, leaving bin/ at the root.
    bin.install Dir["bin/helmwart-*"].reject { |f| f.end_with?(".sha256") }.first => "helmwart"
  end

  test do
    # --version only. Every command that does real work needs an account, and a
    # formula test runs in a sandbox with no session — the old test ran a scan
    # and would now fail on authentication rather than on anything about the
    # build.
    assert_match version.to_s, shell_output("#{bin}/helmwart --version")
  end
end
