# GENERATED by scripts/gen-homebrew-formula.mjs from
# packages/cli/binaries/manifest.json. Do not edit by hand — the url, version and
# five SHA-256 values change every release, and a hash somebody retyped is a hash
# nobody can trust.
#
# It fetches the npm platform tarballs, which is where the binaries already
# live — one place, one set of bytes, no GitHub release to create or keep in
# step. Publish this file to the tap repo KodyMike/homebrew-helmwart as
# Formula/helmwart.rb. Users then run:
#   brew tap kodymike/helmwart
#   brew install helmwart
#
# The macOS binaries are signed with a Developer ID and notarised by Apple, so
# Gatekeeper accepts them; `spctl -a -vv` answers "source=Notarized Developer
# ID". They are not stapled, because a bare executable has nowhere to hold a
# ticket — Gatekeeper fetches it from Apple instead. See
# docs/runbooks/signing-macos.md.
class Helmwart < Formula
  desc "Design-time threat modeling for agentic-AI systems, in your CI"
  homepage "https://helmwart.com/cli/"
  version "0.5.3"
  license :cannot_represent # proprietary, free to use — see LICENSE

  on_macos do
    on_arm do
      url "https://registry.npmjs.org/@helmwart/cli-darwin-arm64/-/cli-darwin-arm64-0.5.3.tgz"
      sha256 "4debbdbccd5eb9c39ef45b58f46d8ca762a8fac39ffd9722ae399c96776396b3"
    end
    on_intel do
      url "https://registry.npmjs.org/@helmwart/cli-darwin-x64/-/cli-darwin-x64-0.5.3.tgz"
      sha256 "4cfdcd0f2e414ffbb280504756330ce76fa0c30e3e42e38b9fe0f834207c0189"
    end
  end

  on_linux do
    on_arm do
      url "https://registry.npmjs.org/@helmwart/cli-linux-arm64/-/cli-linux-arm64-0.5.3.tgz"
      sha256 "eb372dc0f1c889404002a45bcea5d71cbb3ec6821c572bd21c89b3307b1c6e3f"
    end
    on_intel do
      url "https://registry.npmjs.org/@helmwart/cli-linux-x64/-/cli-linux-x64-0.5.3.tgz"
      sha256 "747dfc5fcdb2c73ad75e67a04a7ff2f15429bf0ad53251d342d8b96a5ca0ff01"
    end
  end

  # No `depends_on "node"`. The old formula shelled out to node against a
  # readable .mjs bundle; these are self-contained binaries with the runtime
  # compiled in, which is the point of shipping them.

  def install
    # An npm tarball extracts to a single top-level directory that Homebrew
    # strips, leaving bin/ at the root.
    bin.install Dir["bin/helmwart-*"].reject { |f| f.end_with?(".sha256") }.first => "helmwart"
  end

  test do
    # --version only. Every command that does real work needs an account, and a
    # formula test runs in a sandbox with no session — the old test ran a scan
    # and would now fail on authentication rather than on anything about the
    # build.
    assert_match version.to_s, shell_output("#{bin}/helmwart --version")
  end
end
